input:
  reactionCSV: reactionDF.csv
output:
  fileNamePrefix: starter_00037
scoring:
  testMode: false
  testRows: 100
  useMultiprocessing: false
  max_cores: 1
  mpChunkSize: 64
  cacheSize: 200000
