doranetPath: /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/SynThera/doranet
outputDir: .
baseJobPrefix: BacillusAnthracis_pathway
generationSuffixTemplate: _wGen{generation}
generationsToRun:
- 1
- 2
- 3
searchDepthEqualsGeneration: true
maxNumRxnsEqualsGeneration: true
filterExactNumRxns: true
exactNumRxnsEqualsGeneration: true
numParallelJobs: 16
numProcess: 1
targetsCsvPath: /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/SynThera/BacillusAnthracis/Results_BacillusAnthracis/BacillusAnthracis_generatedCompounds_top20.csv
startersColumn: starter_Canonical_SMILES
targetsColumn: Canonical_SMILES
targetsToTest: null
atomMultiplier: 1.5
helpers:
- C#N
- N
- S
- '[H][H]'
- O=S=O
- N#CO
- O=S(=O)(O)O
- '[Br][Br]'
- O=NO
- O
- C=O
- 'NO'
- N#N
- CO
- O=[N+]([O-])O
- O=S(O)O
- Br
- O=O
- O=C=O
- '[C-]#[O+]'
- C=C
direction: forward
ruleset: JN3604IMT
minRxnAtomEconomy: 0.0
sanitize: true
removePureHelpersRxns: false
transformEnolsFlag: false
considerNameDifference: true
runRanking: true
runVisualization: false
summaryCsv: job_summary.csv
weights: null
coolReactions: null
reaxysResultName: null
excludeSmiles: null
reaxysRxnColor: blue
normalRxnColor: black
